### ISSUE TITLE
Add common logger for both the apps

### ISSUE THREAD

**Issue by Himan10** [null-open-security-community/null-jobs-backend-2.0#18]
1. We have to implement logging for both the apps we have currently i.e., Accounts and Jobs
2. Before implementation, it's recommended to discuss  with the team about how we are going to add this, and which logging modules are we going to use.

**Comment by Himan10** [comment]
@mr-robot369 you've to take actions for this task

**Comment by YogeshUpdhyay** [comment]
A separate issue for JSON logging is being implemented with app-wide scope.
