### ISSUE TITLE
Replace ORM with the SQL queries

### ISSUE THREAD

**Issue by Himan10** [null-open-security-community/null-jobs-backend-2.0#20]
1. Currently in the backend implementation of NullJobs we are using ORM queries to communicate with the database, once a basic prototype is completed, we have to replace these ORM queries with the SQL ones for more better efficiency. 
2. Discuss about this with the team.

**Comment by YogeshUpdhyay** [comment]
For the relations declared between the entities we are sticking with the ORM queries for now.
